path: E:\Deep Learning & Generative AI\Projects\Instance Segmentation Yolo-v11\Dhaka-Traffic-Detection-Yolo_V11\data
train: images\train  # Training images
val: images\val      # Validation images
nc: 21
names: ["ambulance","auto rickshaw", "bicycle"," bus", "car", "garbagevan", "human hauler", "minibus", "minivan", "motorbike", "Pickup", "army vehicle", "policecar", "rickshaw", "scooter", "suv", "taxi", "three wheelers (CNG)", "truck" , "van" , "wheelbarrow"]
